nome = input("\nDigite um funcionário: ")
empresa = input("\nDigite a instituição: ")
qtde_funcionarios = int(input("\nDigite a quantidade de funcionários: "))
mediaMensalidade = float(input("\nDigite a média da mensalidade: "))
print("\n" + nome + " trabalha na empresa " + empresa)
print("\nPossui: ", qtde_funcionarios, "funcionários.")
print("\nA média da mensalidade é de: " + str(mediaMensalidade))
print("\n=====verifique os tipos de dados abaixo:=====")
print("\nO tipo de dado da variável [nome] é: ", type(nome))
print("\nO tipo de dado da variável [empresa] é: ", type(empresa))
print("\nO tipo de dado da variável [qtde_funcionarios] é: ", type(qtde_funcionarios))
print("\nO tipo de dado da variável [mediaMensalidade] é: ", type(mediaMensalidade))